---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
http.host: 0.0.0.0

# Habilita o monitoramento pelo Kibana
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://10.12.2.246:9200"]
xpack.monitoring.elasticsearch.username: "logstash_internal"
xpack.monitoring.elasticsearch.password: "${LOGSTASH_INTERNAL_PASSWORD}"

node.name: logstash
